insert into tech values (gen_random_uuid(), 'JS', now());
insert into tech values (gen_random_uuid(), 'TS', now());
insert into tech values (gen_random_uuid(), 'Vue.js', now());
insert into tech values (gen_random_uuid(), 'React', now());
insert into tech values (gen_random_uuid(), 'Svelte', now());
insert into tech values (gen_random_uuid(), 'Java', now());
insert into tech values (gen_random_uuid(), 'Spring', now());
insert into tech values (gen_random_uuid(), 'Spring WebMVC', now());
insert into tech values (gen_random_uuid(), 'Spring Data JPA', now());
insert into tech values (gen_random_uuid(), 'Spring Security', now());
insert into tech values (gen_random_uuid(), 'Kotlin', now());
insert into tech values (gen_random_uuid(), 'Jetpack Compose', now());
insert into tech values (gen_random_uuid(), 'Swift', now());
insert into tech values (gen_random_uuid(), 'Swift UI', now());
insert into tech values (gen_random_uuid(), 'CSS', now());
insert into tech values (gen_random_uuid(), 'Sass', now());
insert into tech values (gen_random_uuid(), 'Less', now());
insert into tech values (gen_random_uuid(), 'HTML', now());
insert into tech values (gen_random_uuid(), 'Post CSS', now());
insert into tech values (gen_random_uuid(), 'Tailwind CSS', now());
insert into tech values (gen_random_uuid(), 'Python', now());
insert into tech values (gen_random_uuid(), 'Fast Api', now());
insert into tech values (gen_random_uuid(), 'Django', now());
insert into tech values (gen_random_uuid(), 'Yaml', now());
insert into tech values (gen_random_uuid(), 'Xml', now());

insert into tag values (gen_random_uuid(), 'Bug fix', now());
insert into tag values (gen_random_uuid(), 'Polyfill', now());
insert into tag values (gen_random_uuid(), 'Migration', now());
insert into tag values (gen_random_uuid(), 'Feature', now());
insert into tag values (gen_random_uuid(), 'Front-end', now());
insert into tag values (gen_random_uuid(), 'Back-end', now());
insert into tag values (gen_random_uuid(), 'Analytics', now());
insert into tag values (gen_random_uuid(), 'Math statistic', now());
insert into tag values (gen_random_uuid(), 'ML', now());
insert into tag values (gen_random_uuid(), 'LLM', now());

